version: '3'
services:
  drupal:
    image: drupal:latest
    ports:
      - "80:80"
    volumes:
      - "./drupal:/var/www/html"
    environment:
      - DB_HOST=db
      - DB_USER=drupal
      - DB_PASSWORD=drupal
      - DB_NAME=drupal
    networks:
      - drupal
    links:
      - db:postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - drupal

volumes:
  pgdata:
networks:
  drupal:
    driver: bridge

